### ISSUE TITLE
Diagrama de Clases

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-Band-hi#1]
[Práctica 4 - Diagrama de Clases.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-Band-hi/files/8454718/Practica.4.-.Diagrama.de.Clases.pdf)

**Comment by DuilioAquino10** [comment]
CALIFICACIÓN: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
